name: BuildersWand
author: Wythe
version: 2.18.3
main: de.False.BuildersWand.Main
softdepend: [Lands, ItemsAdder, ASkyBlock, WorldGuard, Towny, GriefPrevention, Factions, mcMMO, BentoBox, PlotSquared, CoreProtect]
api-version: 1.13
commands:
  builderswand:
    description: The general BuildersWand command.
    usage: /builderswand
    aliases: [bw]